
server.port=8080
##http://localhost:8080/h2-console
spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:file:c:/h2/CarStore
spring.datasource.url=jdbc:mysql://localhost:3306/domaindb
#./data/demodb
#spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.username=root
spring.datasource.password=admin@123
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# payment gateway keys
razorpay.api.key=rzp_test_bNZDQ0alDLYS05
razorpay.api.secret=tjXGgBf9BjIZBOVfpax9hMDp
currency=INR


#Hibernate properties

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

spring.devtools.livereload.enabled=true
